require('./identity.spec');
require('./constantly.spec');
require('./inc.spec');
require('./dec.spec');
require('./is-even.spec');
require('./is-odd.spec');
require('./comp.spec');
require('./partial.spec');
require('./curry.spec');
